### ISSUE TITLE
Add a configuration

### ISSUE THREAD

**Issue by thibault-cne** [thibault-cne/dnsr#1]
Add a complete configuration of the dns server.

Configuration will be a yaml file with the following spec:

```yaml
tsig_folder: string
domain_file: string

log:
   level: LogLevel
   color: boolean
```
