### ISSUE TITLE
Change the config file 

### ISSUE THREAD

**Issue by thibault-cne** [thibault-cne/dnsr#19]
Merge the `domains.yml` and `config.yml` file in one to make it more handy to users.

The `config.yml` file should contain a `keys` field following this model:

```yaml
keys:
   key1:
      - domains1.com
      - domains2.com
   key2:
      - domains3.com
```
